version: 2

sources:
  - name: silver
    database: main # Unity Catalog
    schema: demo_silver
    tables:
      - name: customers
        description: "Customer master data from source system"
        columns:
          - name: customer_id
            description: "Natural key for customer"
            tests:
              - unique
              - not_null
          - name: first_name
          - name: last_name
          - name: email
          - name: address
          - name: updated_at

      - name: products
        description: "Product catalog from source system"
        columns:
          - name: product_id
            description: "Natural key for product"
            tests:
              - unique
              - not_null
          - name: name
          - name: category
          - name: unit_cost
          - name: updated_at

      - name: orders
        description: "Order headers"
        columns:
          - name: order_id
            tests:
              - unique
              - not_null
          - name: customer_id
          - name: order_date
          - name: status
          - name: updated_at

      - name: order_items
        description: "Order line items"
        columns:
          - name: order_item_id
            tests:
              - unique
              - not_null
          - name: order_id
          - name: product_id
          - name: quantity
          - name: sales_amount
