import os
import tempfile
import uuid

from pyspark.sql import SparkSession

from kimball.orchestration.orchestrator import Orchestrator


def test_schema_evolution_with_new_column(spark: SparkSession):
    """
    Integration test for schema evolution: Add a new column to source and verify
    SCD2 merge and IDENTITY columns handle it gracefully.
    """
    db_name = f"test_db_{uuid.uuid4().hex[:8]}"
    spark.sql(f"CREATE DATABASE IF NOT EXISTS {db_name}")

    with tempfile.TemporaryDirectory() as temp_dir:
        config_path = os.path.join(temp_dir, "test_config.yml")

        initial_config = f"""
table_name: {db_name}.dim_customer
table_type: dimension
scd_type: 2
keys:
  surrogate_key: customer_sk
  natural_keys: [customer_id]
surrogate_key_strategy: identity
track_history_columns: [first_name, last_name]
sources:
  - name: {db_name}.customers
    alias: c
    cdc_strategy: full
transformation_sql: |
  SELECT
    c.customer_id,
    c.first_name,
    c.last_name
  FROM c
"""

        with open(config_path, "w") as f:
            f.write(initial_config)

        spark.sql(f"""
        CREATE TABLE {db_name}.customers (
            customer_id INT,
            first_name STRING,
            last_name STRING
        ) USING DELTA
        """)

        spark.sql(f"""
        INSERT INTO {db_name}.customers VALUES
        (1, 'John', 'Doe'),
        (2, 'Jane', 'Smith')
        """)

        os.environ["KIMBALL_ETL_SCHEMA"] = db_name
        orchestrator = Orchestrator(config_path, spark=spark)
        result = orchestrator.run()
        assert result["status"] == "SUCCESS"

        ddl_rows = spark.sql(f"DESCRIBE EXTENDED {db_name}.dim_customer").collect()
        ddl_text = "\n".join([row[0] for row in ddl_rows])
        is_databricks = bool(__import__("os").environ.get("DATABRICKS_RUNTIME_VERSION") or __import__("os").environ.get("DATABRICKS_HOST"))
        if is_databricks:
            assert (
                "GENERATED BY DEFAULT AS IDENTITY" in ddl_text
                or "GENERATED ALWAYS AS IDENTITY" in ddl_text
            ), f"Expected IDENTITY column on Databricks, got:\n{ddl_text}"
        else:
            assert "customer_sk" in ddl_text, f"Expected customer_sk column, got:\n{ddl_text}"

        evolved_config = f"""
table_name: {db_name}.dim_customer
table_type: dimension
scd_type: 2
keys:
  surrogate_key: customer_sk
  natural_keys: [customer_id]
surrogate_key_strategy: identity
track_history_columns: [first_name, last_name, email]
schema_evolution: true
sources:
  - name: {db_name}.customers
    alias: c
    cdc_strategy: full
transformation_sql: |
  SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    c.email
  FROM c
"""

        spark.sql(f"""
        ALTER TABLE {db_name}.customers ADD COLUMN email STRING
        """)

        spark.sql(f"""
        UPDATE {db_name}.customers SET email = 'john@example.com' WHERE customer_id = 1
        """)

        spark.sql(f"""
        UPDATE {db_name}.customers SET email = 'jane@example.com' WHERE customer_id = 2
        """)

        with open(config_path, "w") as f:
            f.write(evolved_config)

        orchestrator = Orchestrator(config_path, spark=spark)
        result = orchestrator.run()
        assert result["status"] == "SUCCESS"

        evolved_schema = spark.table(f"{db_name}.dim_customer").schema
        email_field = next(
            (f for f in evolved_schema.fields if f.name == "email"), None
        )
        assert email_field is not None

        data = spark.table(f"{db_name}.dim_customer").collect()
        sk_values = [row.customer_sk for row in data]
        assert len(set(sk_values)) == len(sk_values)

        spark.sql(f"DROP TABLE {db_name}.dim_customer")
        spark.sql(f"DROP TABLE {db_name}.customers")

    spark.sql(f"DROP DATABASE IF EXISTS {db_name} CASCADE")
