#!/usr/bin/env python3
"""
Analyze Databricks query history to identify unnecessary or wasteful SQL
operations generated by the Kimball Framework.

Queries ``system.query.history`` (configurable window) via the Databricks
Statement Execution API and classifies each statement into a pattern bucket.
Reports volume/duration by category, redundant ("waste") operations, query
source breakdown, and the worst queries.

Databricks-only. Classification is by SQL text: the framework's batch_id lives
on Delta *commits* (``commitInfo.userMetadata``), not on
``system.query.history`` rows, so tag-based attribution of query rows is not
possible today (see ROADMAP 1.4 for the framework query-tag follow-up).

Usage::

    # Requires DATABRICKS_HOST and DATABRICKS_TOKEN in the environment or .env
    python tools/query_history.py                 # last 7 days
    python tools/query_history.py --days 30 --warehouse wh123
    python tools/query_history.py --json
    python tools/query_history.py --verbose        # print the executed SQL

Dependencies: databricks-sdk >= 0.30.0  (pip install '.[remote]')
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import textwrap
import time
from collections import Counter, defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent

# --------------------------------------------------------------------------- #
# Query pattern classification
# --------------------------------------------------------------------------- #

_PATTERN_SCORING: dict[str, str] = {
    "MERGE": "table mutation",
    "INSERT": "table mutation",
    "UPDATE": "table mutation",
    "DELETE": "table mutation",
    "SELECT": "data read",
    "DESCRIBE": "metadata / discovery",
    "SHOW": "metadata / discovery",
    "CACHE TABLE": "maybe unnecessary",
    "PERSIST TABLE": "maybe unnecessary",
    "ALTER": "DDL",
    "DROP": "DDL",
    "CREATE": "DDL",
    "SET": "configuration",
    "USE": "configuration",
    "EXPLAIN": "compile-time check (skip)",
}

_SQL_KEYWORDS = frozenset(
    {
        "MERGE",
        "SELECT",
        "INSERT",
        "CREATE",
        "ALTER",
        "DELETE",
        "UPDATE",
        "DESCRIBE",
        "SHOW",
        "DROP",
        "EXPLAIN",
        "CACHE",
        "PERSIST",
        "SET",
        "USE",
        "REPLACE",
        "COPY",
        "OPTIMIZE",
        "VACUUM",
        "GRANT",
        "REVOKE",
        "TRUNCATE",
        "RENAME",
        "ANALYZE",
    }
)

# (regex, label) - redundant / wasteful SQL operations.
_WASTE_PATTERNS: list[tuple[re.Pattern, str]] = [
    (
        re.compile(r"DESCRIBE\s+HISTORY\s+\S+\s+LIMIT\s+1", re.I),
        "describe_history_probe",
    ),
    (re.compile(r"SHOW\s+COLUMNS\s+IN\s+\S+", re.I), "show_columns"),
    (re.compile(r"DESCRIBE\s+TABLE\s+\S+", re.I), "describe_table"),
    (re.compile(r"CACHE\s+TABLE|PERSIST\s+TABLE", re.I), "cache_or_persist"),
    (re.compile(r"SELECT\s+COUNT\(\*\)\s+FROM", re.I), "select_count"),
    (re.compile(r"SELECT\s+COUNT\(\*\)", re.I), "select_count"),
    (re.compile(r"SELECT\s+MAX\(.*version", re.I), "max_version"),
    (re.compile(r"TABLE\s+\S+\.\S+\s+IS\s+NOT\s+NULL", re.I), "is_not_null"),
    (re.compile(r"ALTER\s+TABLE\s+\S+\s+ADD\s+COLUMNS", re.I), "alter_add_column"),
    (re.compile(r"ALTER\s+TABLE\s+\S+\s+ALTER\s+COLUMN", re.I), "alter_column"),
    (re.compile(r"DESCRIBE\s+HISTORY", re.I), "describe_history"),
    (
        re.compile(r"UPDATE\s+\S+\s+SET\s+`?\w+`?\s*=\s*'Missing'", re.I),
        "null_backfill",
    ),
    (re.compile(r"STACK_TRACE\s*=", re.I), "stack_trace_probe"),
]


def _classify(text: str) -> tuple[str, str]:
    """Return ``(category, waste_label_or_empty)`` for a statement text."""
    text_stripped = text.strip().upper()
    first_word = text_stripped.split(None, 1)[0] if text_stripped else ""
    # Skip non-SQL fragments (Python code logged by Spark Connect clients).
    if (
        first_word
        and first_word not in _SQL_KEYWORDS
        and first_word.startswith(("SELF", "SPARK", "DF"))
    ):
        return ("python_code", "")
    for pattern, label in _WASTE_PATTERNS:
        if pattern.search(text):
            return ("waste", label)
    return next(
        (
            (category, "")
            for keyword, category in sorted(
                _PATTERN_SCORING.items(), key=lambda x: -len(x[0])
            )
            if text_stripped.startswith(keyword)
        ),
        ("other", ""),
    )


# --------------------------------------------------------------------------- #
# Query history fetcher
# --------------------------------------------------------------------------- #

_COLUMNS = (
    "statement_id",
    "statement_text",
    "statement_type",
    "execution_status",
    "client_application",
    "execution_duration_ms",
    "total_duration_ms",
    "read_rows",
    "produced_rows",
    "read_files",
    "written_bytes",
    "start_time",
    "error_message",
)

# Max time to wait for a statement to finish (the execute() call already waits
# up to its own wait_timeout; this caps the poll loop afterwards).
_POLL_DEADLINE_SECONDS = 600


def _to_int(value: Any) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return 0


def _col_map(result: Any) -> dict[str, int]:
    """Map column name -> position from the statement result schema, falling
    back to the declared SELECT order when the schema is unavailable."""
    try:
        cols = result.result.schema.columns
        if mapped := {c.name: i for i, c in enumerate(cols)}:
            return mapped
    except Exception:  # noqa: BLE001 - schema shape varies across SDK versions
        pass
    return {name: i for i, name in enumerate(_COLUMNS)}


def _row_to_dict(item: Any, col_map: dict[str, int]) -> dict[str, Any]:
    def val(name: str, pos: int) -> Any:
        idx = col_map.get(name, pos)
        return item[idx] if idx is not None and idx < len(item) else None

    return {
        "statement_id": str(val("statement_id", 0) or ""),
        "statement_text": str(val("statement_text", 1) or ""),
        "statement_type": str(val("statement_type", 2) or ""),
        "execution_status": str(val("execution_status", 3) or ""),
        "client_application": str(val("client_application", 4) or "unknown"),
        "execution_duration_ms": _to_int(val("execution_duration_ms", 5)),
        "total_duration_ms": _to_int(val("total_duration_ms", 6)),
        "read_rows": _to_int(val("read_rows", 7)),
        "produced_rows": _to_int(val("produced_rows", 8)),
        "read_files": _to_int(val("read_files", 9)),
        "written_bytes": _to_int(val("written_bytes", 10)),
        "start_time": str(val("start_time", 11) or ""),
        "error_message": str(val("error_message", 12) or ""),
    }


def _find_warehouse(ws: Any) -> str:
    for w in ws.warehouses.list():
        if w.state == "RUNNING":
            return str(w.id)
    raise RuntimeError("No running warehouse found. Start one in the Databricks UI.")


def _fetch_history(
    ws: Any,
    *,
    days: int = 7,
    warehouse_id: str | None = None,
    verbose: bool = False,
) -> list[dict[str, Any]]:
    """Fetch query history rows from ``system.query.history``."""
    from databricks.sdk.service.sql import StatementState

    cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()
    sql = textwrap.dedent(
        f"""\
        SELECT
          statement_id,
          statement_text,
          statement_type,
          execution_status,
          client_application,
          execution_duration_ms,
          total_duration_ms,
          read_rows,
          produced_rows,
          read_files,
          written_bytes,
          start_time,
          error_message
        FROM system.query.history
        WHERE start_time >= '{cutoff}'
          AND statement_text IS NOT NULL
          AND statement_text NOT LIKE '%system.query.history%'
        ORDER BY total_duration_ms DESC
        """
    )
    if verbose:
        print(f"Executing:\n{sql[:500]}", file=sys.stderr)

    statement = ws.statement_execution.execute_statement(
        statement=sql,
        warehouse_id=warehouse_id or _find_warehouse(ws),
        wait_timeout="50s",
    )
    deadline = time.time() + _POLL_DEADLINE_SECONDS
    result = ws.statement_execution.get_statement(statement.statement_id)
    terminal = (
        StatementState.SUCCEEDED,
        StatementState.FAILED,
        StatementState.CANCELED,
    )
    while result.status.state not in terminal and time.time() < deadline:
        time.sleep(2)
        result = ws.statement_execution.get_statement(statement.statement_id)

    if result.status.state != StatementState.SUCCEEDED:
        error = getattr(result.status, "error", None)
        msg = getattr(error, "message", "unknown") if error else "unknown"
        raise RuntimeError(f"query failed: {msg}")

    rr = result.result
    if not rr or not rr.data_array:
        return []
    col_map = _col_map(result)
    return [_row_to_dict(item, col_map) for item in rr.data_array]


# --------------------------------------------------------------------------- #
# Analysis
# --------------------------------------------------------------------------- #


def _analyze(rows: list[dict[str, Any]], *, days: int) -> dict[str, Any]:
    """Run analysis over fetched rows and return a report dict."""
    total_queries = len(rows)
    total_duration = sum(r["total_duration_ms"] for r in rows)
    total_exec = sum(r["execution_duration_ms"] for r in rows)

    pattern_counter: Counter[str] = Counter()
    category_duration: dict[str, float] = defaultdict(float)
    waste_counter: Counter[str] = Counter()
    waste_duration: dict[str, float] = defaultdict(float)
    client_counter: Counter[str] = Counter()

    for row in rows:
        category, waste_label = _classify(row["statement_text"])
        pattern_counter[category] += 1
        category_duration[category] += row["total_duration_ms"]
        client_counter[row["client_application"]] += 1
        if category == "waste":
            waste_counter[waste_label] += 1
            waste_duration[waste_label] += row["total_duration_ms"]

    worst = sorted(rows, key=lambda r: r["total_duration_ms"], reverse=True)[:20]
    client_summary = (
        {
            app: {"count": count, "pct": round(count / total_queries * 100, 1)}
            for app, count in client_counter.most_common()
        }
        if total_queries
        else {}
    )

    waste_total = sum(waste_duration.values())
    return {
        "window_days": days,
        "total_queries": total_queries,
        "total_duration_seconds": round(total_duration / 1000, 2),
        "total_execution_seconds": round(total_exec / 1000, 2),
        "avg_duration_seconds": round(total_duration / 1000 / total_queries, 3)
        if total_queries
        else 0,
        "by_category": {
            cat: {
                "count": count,
                "duration_seconds": round(category_duration[cat] / 1000, 2),
            }
            for cat, count in pattern_counter.most_common()
        },
        "waste": {
            "by_type": {
                label: {
                    "count": waste_counter[label],
                    "duration_seconds": round(waste_duration[label] / 1000, 2),
                }
                for label in waste_counter
            },
            "total_waste_seconds": round(waste_total / 1000, 2),
            "waste_pct": round(waste_total / total_duration * 100, 1)
            if total_duration
            else 0,
        },
        "by_client_application": client_summary,
        "worst_queries": [
            {
                "statement_text": r["statement_text"][:200],
                "duration_seconds": round(r["total_duration_ms"] / 1000, 2),
                "client_application": r["client_application"],
                "start_time": r["start_time"],
            }
            for r in worst
        ],
    }


def _print_report(report: dict[str, Any]) -> None:
    sep = "=" * 70
    dash = "-" * 70
    print()
    print(sep)
    print("  QUERY HISTORY ANALYSIS")
    print(sep)
    print(f"\n  Window (days):         {report['window_days']}")
    print(f"  Total queries:         {report['total_queries']}")
    print(f"  Wall-clock duration:   {report['total_duration_seconds']}s")
    print(f"  Execution duration:    {report['total_execution_seconds']}s")
    print(f"  Avg per query:         {report['avg_duration_seconds']}s")

    print(f"\n{dash}")
    print("  BY CATEGORY")
    print(dash)
    for cat, info in report["by_category"].items():
        print(
            f"  {cat:30s} {info['count']:5d} queries  {info['duration_seconds']:10.2f}s"
        )

    waste = report["waste"]
    if waste["total_waste_seconds"] > 0:
        print(f"\n{dash}")
        print(
            f"  WASTE / REDUNDANT OPERATIONS  ({waste['waste_pct']}% of total duration)"
        )
        print(dash)
        for label, info in waste["by_type"].items():
            print(
                f"  {label:30s} {info['count']:5d}x  {info['duration_seconds']:10.2f}s"
            )
        print(f"  {'TOTAL':30s} {'':5s} {waste['total_waste_seconds']:10.2f}s")

    print(f"\n{dash}")
    print("  BY CLIENT APPLICATION")
    print(dash)
    for app, info in report["by_client_application"].items():
        label = app if len(app) <= 40 else f"{app[:37]}..."
        print(f"  {label:40s} {info['count']:5d} ({info['pct']:5.1f}%)")

    print(f"\n{dash}")
    print("  WORST QUERIES (top 20 by duration)")
    print(dash)
    for i, q in enumerate(report["worst_queries"], 1):
        print(f"  {i:2d}. {q['duration_seconds']:8.2f}s  [{q['client_application']}]")
        print(f"      {q['statement_text'][:120].strip()}")
        print()


# --------------------------------------------------------------------------- #
# Entry point (shared by the CLI and the standalone script)
# --------------------------------------------------------------------------- #


def _load_env_file(env_file: str | None) -> None:
    if env_file is None:
        env_file = str(REPO_ROOT / ".env")
    if not os.path.exists(env_file):
        return
    try:
        from dotenv import load_dotenv

        load_dotenv(env_file, override=True)
        print(f"[query-history] loaded environment from {env_file}", file=sys.stderr)
    except ImportError:
        pass


def run(
    *,
    days: int = 7,
    warehouse: str | None = None,
    json_output: bool = False,
    verbose: bool = False,
    env_file: str | None = None,
) -> int:
    """Run query-history analysis. Returns a process exit code."""
    _load_env_file(env_file)
    host = os.environ.get("DATABRICKS_HOST")
    token = os.environ.get("DATABRICKS_TOKEN")
    if not host or not token:
        print(
            "error: DATABRICKS_HOST and DATABRICKS_TOKEN must be set", file=sys.stderr
        )
        return 1
    try:
        from databricks.sdk import WorkspaceClient

        ws = WorkspaceClient(host=host, token=token)
    except ImportError:
        print(
            "error: databricks-sdk is not installed. Run: pip install '.[remote]'",
            file=sys.stderr,
        )
        return 1
    except Exception as exc:  # noqa: BLE001 - connection/credential failures
        print(f"error: cannot connect to Databricks: {exc}", file=sys.stderr)
        return 1

    try:
        rows = _fetch_history(ws, days=days, warehouse_id=warehouse, verbose=verbose)
    except Exception as exc:  # noqa: BLE001 - access-denied / retention / warehouse errors
        print(f"error: query history failed: {exc}", file=sys.stderr)
        print(
            "If access was denied, verify your token has the "
            "'databricks_query_history' permission, or reduce --days if retention "
            "has expired.",
            file=sys.stderr,
        )
        return 1

    if not rows:
        print("No queries found in the selected window.")
        return 0

    report = _analyze(rows, days=days)
    if json_output:
        print(json.dumps(report, indent=2, default=str))
    else:
        _print_report(report)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--days", type=int, default=7, help="Days of history (default: 7)"
    )
    parser.add_argument(
        "--warehouse", default=None, help="Warehouse ID (default: first running)"
    )
    parser.add_argument("--json", action="store_true", help="JSON output")
    parser.add_argument(
        "--verbose", action="store_true", help="Show the executed SQL (stderr)"
    )
    parser.add_argument("--env-file", default=None, help="Path to .env file")
    args = parser.parse_args()
    return run(
        days=args.days,
        warehouse=args.warehouse,
        json_output=args.json,
        verbose=args.verbose,
        env_file=args.env_file,
    )


if __name__ == "__main__":
    sys.exit(main())
