from kimball.common.runtime_policy import RuntimePolicy


def test_databricks_policy_uses_identity_ddl_and_sk_exclusion() -> None:
    policy = RuntimePolicy(is_databricks=True)

    assert policy.identity_column_def("surrogate_key") == (
        "surrogate_key BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1)"
    )
    assert policy.cluster_clause(["event_date"], None) == "\nCLUSTER BY (event_date)"
    assert policy.should_include_sk_in_insert() is False


def test_local_policy_uses_plain_bigint_and_includes_sk() -> None:
    policy = RuntimePolicy(is_databricks=False)

    assert policy.identity_column_def("surrogate_key") == "surrogate_key BIGINT"
    assert policy.cluster_clause(None, ["event_date"]) == "\nPARTITIONED BY (event_date)"
    assert policy.should_include_sk_in_insert() is True
